### ISSUE TITLE
Cuál es el service que hace que puedas mandar tu Rate de un product?  Cómo hacemos con las Categories?

### ISSUE THREAD

**Issue by Brujitari** [TheBridge-FullStackDeveloper/ecommerce-back#25]
creo que rate no debería estar como campo obligatorio que mande el front en el body porque eso lo mandamos al comprar un producto no al publicarlo o actualizarlo, osea sería en tal caso en los service de orders(?)
category quizás debería ser una opción entre varias existentes de un dropdown o así, porque si lo manda el cliente por el body podemos tener mucho caos en las categorías

_Originally posted by @Brujitari in https://github.com/TheBridge-FullStackDeveloper/ecommerce-back/pull/17#discussion_r915176559_

**Comment by jaengustavof** [comment]
@Brujitari el service ser'ia el de update. Donde podemos agregar o modificar cualquier informaci'on relacionada al producto.
